/**
 * Data types for the FakeStore API (https://fakestoreapi.com).
 * Keeping types separate from the client makes them easy to reuse
 * in both tests and schema validators.
 */

export interface Rating {
  rate: number;
  count: number;
}

export interface Product {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: Rating;
}

// Payload for creating or updating a product, without id and rating (generated by the server).
export type ProductPayload = Omit<Product, 'id' | 'rating'>;

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  token: string;
}
